console.error('Do not include this file, only for test auto-completion')

let f = (needle, msg) => Object.prototype.should

Object.prototype.should = {
    a: f,
    an: f,
    any: f,
    and: f,
    all: f,
    arguments: f,
    be: f,
    deep: f,
    include: f,
    ok: f,
    equal: f,
    true: f,
    false: f,
    null: f,
    undefined: f,
    exist: f,
    empty: f,
    property: f,
    instanceOf: f,
    to: f,
    not: f,
    eql: f,
    above: f,
    least: f,
    below: f,
    most: f,
    within: f,
    ownProperty: f,
    length: f,
    match: f,
    string: f,
    keys: f,
    throw: f,
    respondTo: f,
    itself: f,
    satisfy: f,
    closeTo: f,
    members: f,
    change: f,
    increase: f,
    descrease: f,
    have: f
}